export interface Kaomoji {
  id: string
  text: string
  category: string
  keywords: string[]
}

export const KAOMOJI_CATEGORIES = [
  'Happy',
  'Sad',
  'Angry',
  'Love',
  'Confused',
  'Surprised',
  'Action',
  'Greetings',
  'Sleeping',
  'Apology',
  'Magic',
  'Dancing',
  'Food',
  'Music',
  'Study',
  'Cats',
  'Bears',
  'Dogs',
  'Rabbits',
  'Friends',
  'Skeptical',
  'Cute',
  'Shy',
  'Sympathy',
] as const

export type KaomojiCategory = typeof KAOMOJI_CATEGORIES[number]

export const KAOMOJI_LIST: Kaomoji[] = [
  // Happy (30+)
  { id: 'h1', text: '(^_^)', category: 'Happy', keywords: ['smile', 'happy'] },
  { id: 'h2', text: '(^o^)', category: 'Happy', keywords: ['smile', 'happy', 'laugh'] },
  { id: 'h3', text: '(uwu)', category: 'Happy', keywords: ['cute', 'happy', 'uwu'] },
  { id: 'h4', text: '(*^ω^)', category: 'Happy', keywords: ['cute', 'happy'] },
  { id: 'h5', text: '(✿◠‿◠)', category: 'Happy', keywords: ['flower', 'happy'] },
  { id: 'h6', text: 'd(^_^)b', category: 'Happy', keywords: ['thumbs up', 'music'] },
  { id: 'h7', text: 'ヽ(・∀・)ﾉ', category: 'Happy', keywords: ['yay', 'happy'] },
  { id: 'h8', text: '(｡♥‿♥｡)', category: 'Happy', keywords: ['love', 'happy'] },
  { id: 'h9', text: 'o(>ω<)o', category: 'Happy', keywords: ['excited'] },
  { id: 'h10', text: '(っ˘ω˘ς )', category: 'Happy', keywords: ['content'] },
  { id: 'h11', text: '(≧◡≦)', category: 'Happy', keywords: ['happy', 'cute'] },
  { id: 'h12', text: '(⌒▽⌒)☆', category: 'Happy', keywords: ['star', 'happy'] },
  { id: 'h13', text: '<(￣︶￣)>', category: 'Happy', keywords: ['proud', 'happy'] },
  { id: 'h14', text: '(*・ω・)ﾉ', category: 'Happy', keywords: ['wave', 'happy'] },
  { id: 'h15', text: '(´｡• ᵕ •｡`)', category: 'Happy', keywords: ['blush', 'happy'] },
  { id: 'h16', text: '╰(*´︶`*)╯', category: 'Happy', keywords: ['yey', 'happy'] },
  { id: 'h17', text: '(✧ω✧)', category: 'Happy', keywords: ['stars', 'eyes'] },
  { id: 'h18', text: '(◕‿◕)', category: 'Happy', keywords: ['cute', 'smile'] },
  { id: 'h19', text: '(o^▽^o)', category: 'Happy', keywords: ['laugh'] },
  { id: 'h20', text: '(´• ω •`)', category: 'Happy', keywords: ['cute'] },
  { id: 'h21', text: '(⌒ω⌒)', category: 'Happy', keywords: ['smile'] },
  { id: 'h22', text: 'ヽ(o^ ^o)ﾉ', category: 'Happy', keywords: ['hands up'] },
  { id: 'h23', text: '(✯◡✯)', category: 'Happy', keywords: ['excited'] },
  { id: 'h24', text: '(◕‿◕✿)', category: 'Happy', keywords: ['flower'] },
  { id: 'h25', text: '(☆ω☆)', category: 'Happy', keywords: ['star eyes'] },
  { id: 'h26', text: 'ヽ(*・ω・)ﾉ', category: 'Happy', keywords: ['wave'] },
  { id: 'h27', text: '( ´ ▽ ` )', category: 'Happy', keywords: ['relaxed'] },
  { id: 'h28', text: '(￣ω￣)', category: 'Happy', keywords: ['content'] },
  { id: 'h29', text: '╰(▔∀▔)╯', category: 'Happy', keywords: ['yay'] },
  { id: 'h30', text: '(o･ω･o)', category: 'Happy', keywords: ['curious'] },
  { id: 'h31', text: '(´｡• ᵕ •｡`)', category: 'Happy', keywords: ['blush'] },
  { id: 'h32', text: 'ヽ(>∀<☆)ノ', category: 'Happy', keywords: ['excited'] },
  { id: 'h33', text: '(´･ᴗ･ ` )', category: 'Happy', keywords: ['smile'] },
  { id: 'h34', text: '(ﾉ´ヮ`)ﾉ*: ･ﾟ', category: 'Happy', keywords: ['sparkle'] },
  { id: 'h35', text: '( ˙꒳​˙ )', category: 'Happy', keywords: ['neutral happy'] },

  // Sad (25+)
  { id: 's1', text: '(T_T)', category: 'Sad', keywords: ['crying', 'sad'] },
  { id: 's2', text: '(;_;)', category: 'Sad', keywords: ['crying', 'sad'] },
  { id: 's3', text: '(._.)', category: 'Sad', keywords: ['disappointed'] },
  { id: 's4', text: '(ToT)', category: 'Sad', keywords: ['crying'] },
  { id: 's5', text: '(qwq)', category: 'Sad', keywords: ['sad', 'crying'] },
  { id: 's6', text: 'ಥ_ಥ', category: 'Sad', keywords: ['crying'] },
  { id: 's7', text: '(/_;)', category: 'Sad', keywords: ['crying'] },
  { id: 's8', text: '(╥_╥)', category: 'Sad', keywords: ['crying', 'sad'] },
  { id: 's9', text: '(´;ω;`)', category: 'Sad', keywords: ['crying', 'sad'] },
  { id: 's10', text: '(-̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩___-̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩)', category: 'Sad', keywords: ['waterfall tears'] },
  { id: 's11', text: '(｡•́︿•̀｡)', category: 'Sad', keywords: ['sad'] },
  { id: 's12', text: '(个_个)', category: 'Sad', keywords: ['tears'] },
  { id: 's13', text: '(〒﹏〒)', category: 'Sad', keywords: ['crying'] },
  { id: 's14', text: '｡ﾟ(ﾟ´Dv`ﾟ)ﾟ｡', category: 'Sad', keywords: ['sobbing'] },
  { id: 's15', text: '(´-ω-`)', category: 'Sad', keywords: ['disappointed'] },
  { id: 's16', text: '(｡╯3╰｡)', category: 'Sad', keywords: ['sad kiss'] },
  { id: 's17', text: '( ╥ω╥ )', category: 'Sad', keywords: ['tears'] },
  { id: 's18', text: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)', category: 'Sad', keywords: ['heavy rain tears'] },
  { id: 's19', text: 'o(TヘTo)', category: 'Sad', keywords: ['holding back tears'] },
  { id: 's20', text: '(´；д；`)', category: 'Sad', keywords: ['pain'] },
  { id: 's21', text: '(´•̥̥̥д•̥̥̥`)', category: 'Sad', keywords: ['crying'] },
  { id: 's22', text: '(unknown)', category: 'Sad', keywords: ['sad'] },
  { id: 's23', text: '( ≧Д≦)', category: 'Sad', keywords: ['screaming'] },
  { id: 's24', text: '((´д｀))', category: 'Sad', keywords: ['shaking'] },
  { id: 's25', text: '(´Ａ｀。)', category: 'Sad', keywords: ['sigh'] },

  // Angry (20+)
  { id: 'a1', text: '(>_<)', category: 'Angry', keywords: ['angry', 'frustrated'] },
  { id: 'a2', text: '(FAO)', category: 'Angry', keywords: ['angry'] },
  { id: 'a3', text: 'ಠ_ಠ', category: 'Angry', keywords: ['disapproval', 'look'] },
  { id: 'a4', text: '(╬ Ò﹏Ó)', category: 'Angry', keywords: ['angry', 'furious'] },
  { id: 'a5', text: '(¬_¬)', category: 'Angry', keywords: ['suspicious'] },
  { id: 'a6', text: '(＃`Д´)', category: 'Angry', keywords: ['angry', 'shout'] },
  { id: 'a7', text: '(｀ε´)', category: 'Angry', keywords: ['angry', 'pout'] },
  { id: 'a8', text: '(¬､¬)', category: 'Angry', keywords: ['suspicious', 'glare'] },
  { id: 'a9', text: '(*￣m￣)', category: 'Angry', keywords: ['dissatisfied'] },
  { id: 'a10', text: '(￣^￣)', category: 'Angry', keywords: ['hmph'] },
  { id: 'a11', text: '(＃＞＜)', category: 'Angry', keywords: ['pain', 'angry'] },
  { id: 'a12', text: '(°ㅂ°╬)', category: 'Angry', keywords: ['annoyed'] },
  { id: 'a13', text: '(╬￣皿￣)', category: 'Angry', keywords: ['grinding teeth'] },
  { id: 'a14', text: '(҂ `з´ )', category: 'Angry', keywords: ['fighting'] },
  { id: 'a15', text: '(* ಠ_ಠ)', category: 'Angry', keywords: ['serious'] },
  { id: 'a16', text: '(｀Ð´)', category: 'Angry', keywords: ['shout'] },
  { id: 'a17', text: '(╬`益´)', category: 'Angry', keywords: ['rage'] },
  { id: 'a18', text: '凸(￣ヘ￣)', category: 'Angry', keywords: ['rude'] },
  { id: 'a19', text: '(mu_mu)', category: 'Angry', keywords: ['annoyed'] },
  { id: 'a20', text: '(*≧m≦*)', category: 'Angry', keywords: ['mad'] },

  // Love (20+)
  { id: 'l1', text: '(♥_♥)', category: 'Love', keywords: ['love', 'heart'] },
  { id: 'l2', text: '(´ε｀ )', category: 'Love', keywords: ['kiss'] },
  { id: 'l3', text: '(♡μ_μ)', category: 'Love', keywords: ['shy', 'love'] },
  { id: 'l4', text: '(*♡∀♡)', category: 'Love', keywords: ['love', 'eyes'] },
  { id: 'l5', text: '( ˘ ³˘)♥', category: 'Love', keywords: ['kiss', 'love'] },
  { id: 'l6', text: '(❤ω❤)', category: 'Love', keywords: ['love', 'eyes'] },
  { id: 'l7', text: '(´｡• ᵕ •｡`) ♡', category: 'Love', keywords: ['love', 'heart'] },
  { id: 'l8', text: 'ヽ(♡‿♡)ノ', category: 'Love', keywords: ['love', 'happy'] },
  { id: 'l9', text: '(ʃƪ ˘ ³˘)', category: 'Love', keywords: ['kiss'] },
  { id: 'l10', text: '(°◡°♡)', category: 'Love', keywords: ['love'] },
  { id: 'l11', text: '(´∩｡• ᵕ •｡∩`)', category: 'Love', keywords: ['in love'] },
  { id: 'l12', text: '(♡-_-♡)', category: 'Love', keywords: ['love'] },
  { id: 'l13', text: '( ◡‿◡ *)', category: 'Love', keywords: ['shy'] },
  { id: 'l14', text: '(ﾉ´ з `)ノ', category: 'Love', keywords: ['kiss throw'] },
  { id: 'l15', text: '(♡˙︶˙♡)', category: 'Love', keywords: ['peace love'] },
  { id: 'l16', text: '(´ω｀*)', category: 'Love', keywords: ['fond'] },
  { id: 'l17', text: '( ˘⌣˘)♡(˘⌣˘ )', category: 'Love', keywords: ['couple'] },
  { id: 'l18', text: 'Σ>―(〃°ω°〃)♡→', category: 'Love', keywords: ['arrow', 'cupid'] },
  { id: 'l19', text: '(´▽`ʃ♡ƪ)', category: 'Love', keywords: ['hugging heart'] },
  { id: 'l20', text: '(๑♡⌓♡๑)', category: 'Love', keywords: ['love eyes'] },

  // Confused (15+)
  { id: 'c1', text: '(o_O)', category: 'Confused', keywords: ['confused', 'eye'] },
  { id: 'c2', text: '(?)', category: 'Confused', keywords: ['question'] },
  { id: 'c3', text: '┐(￣ヘ￣)┌', category: 'Confused', keywords: ['shrug', 'dunno'] },
  { id: 'c4', text: '¯\\_(ツ)_/¯', category: 'Confused', keywords: ['shrug'] },
  { id: 'c5', text: '(・・ ) ?', category: 'Confused', keywords: ['confused', 'question'] },
  { id: 'c6', text: '(-_-)ゞ゛', category: 'Confused', keywords: ['scratch head'] },
  { id: 'c7', text: '٩(｡•́‿•̀｡)۶', category: 'Confused', keywords: ['dunno', 'cute'] },
  { id: 'c8', text: '(・_・ヾ', category: 'Confused', keywords: ['scratch'] },
  { id: 'c9', text: '┐(︶▽︶)┌', category: 'Confused', keywords: ['who knows'] },
  { id: 'c10', text: '╮(￣ω￣;)╭', category: 'Confused', keywords: ['give up'] },
  { id: 'c11', text: '(・∀・)?', category: 'Confused', keywords: ['question'] },
  { id: 'c12', text: '(?_?)', category: 'Confused', keywords: ['question'] },
  { id: 'c13', text: 'く(＾_・)ゝ', category: 'Confused', keywords: ['scratch'] },
  { id: 'c14', text: '┐(‘～`；)┌', category: 'Confused', keywords: ['dunno'] },
  { id: 'c15', text: 'σ(￣、￣〃)', category: 'Confused', keywords: ['thinking'] },

  // Skeptical (15+)
  { id: 'sk1', text: '(¬_¬)', category: 'Skeptical', keywords: ['suspicious'] },
  { id: 'sk2', text: '(¬､¬)', category: 'Skeptical', keywords: ['side eye'] },
  { id: 'sk3', text: '(￢_￢;)', category: 'Skeptical', keywords: ['doubt'] },
  { id: 'sk4', text: '(⇀_↼)', category: 'Skeptical', keywords: ['doubt'] },
  { id: 'sk5', text: '(￣ω￣;)', category: 'Skeptical', keywords: ['awkward'] },
  { id: 'sk6', text: '(・_・;)', category: 'Skeptical', keywords: ['sweat'] },
  { id: 'sk7', text: '(・_・ヾ', category: 'Skeptical', keywords: ['what'] },
  { id: 'sk8', text: 'Σ(￣。￣ﾉ)', category: 'Skeptical', keywords: ['huh'] },
  { id: 'sk9', text: '(；￢_￢)', category: 'Skeptical', keywords: ['stare'] },
  { id: 'sk10', text: '(￢‿￢ )', category: 'Skeptical', keywords: ['smirk'] },
  { id: 'sk11', text: '(¬‿¬)', category: 'Skeptical', keywords: ['smirk'] },
  { id: 'sk12', text: '(￣ヘ￣)', category: 'Skeptical', keywords: ['hmph'] },
  { id: 'sk13', text: '(<_<)', category: 'Skeptical', keywords: ['side eye'] },
  { id: 'sk14', text: '(>_>)', category: 'Skeptical', keywords: ['side eye'] },
  { id: 'sk15', text: '(￣～￣;)', category: 'Skeptical', keywords: ['thinking'] },

  // Surprised (15+)
  { id: 'su1', text: '(O_O)', category: 'Surprised', keywords: ['shocked'] },
  { id: 'su2', text: '(*_*)', category: 'Surprised', keywords: ['starstruck'] },
  { id: 'su3', text: '∑(O_O;)', category: 'Surprised', keywords: ['scared', 'surprised'] },
  { id: 'su4', text: '(⊙_⊙)', category: 'Surprised', keywords: ['shocked', 'eyes'] },
  { id: 'su5', text: '(ﾟoﾟ)', category: 'Surprised', keywords: ['wide mouth'] },
  { id: 'su6', text: '(o_O) !', category: 'Surprised', keywords: ['surprised'] },
  { id: 'su7', text: 'w(°ｏ°)w', category: 'Surprised', keywords: ['wow'] },
  { id: 'su8', text: 'ヽ(°〇°)ﾉ', category: 'Surprised', keywords: ['woah'] },
  { id: 'su9', text: 'Σ(°ロ°)', category: 'Surprised', keywords: ['shocked'] },
  { id: 'su10', text: '(O.O)', category: 'Surprised', keywords: ['stare'] },
  { id: 'su11', text: 'Σ(□_□)', category: 'Surprised', keywords: ['shocked'] },
  { id: 'su12', text: '(°ロ°)', category: 'Surprised', keywords: ['gasp'] },
  { id: 'su13', text: '(ﾟдﾟ)', category: 'Surprised', keywords: ['shocked'] },
  { id: 'su14', text: '(⊙_⊙)', category: 'Surprised', keywords: ['wide eyes'] },
  { id: 'su15', text: '(ﾉ*0*)ﾉ', category: 'Surprised', keywords: ['oh my'] },

  // Shy (NEW - 15+)
  { id: 'sh1', text: '(⁄ ⁄•⁄ω⁄•⁄ ⁄)', category: 'Shy', keywords: ['blush', 'shy'] },
  { id: 'sh2', text: '(///￣ ￣///)', category: 'Shy', keywords: ['blush'] },
  { id: 'sh3', text: '(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)', category: 'Shy', keywords: ['blush', 'excited'] },
  { id: 'sh4', text: '(*ﾉωﾉ)', category: 'Shy', keywords: ['hiding', 'face'] },
  { id: 'sh5', text: '(*/_＼)', category: 'Shy', keywords: ['hiding'] },
  { id: 'sh6', text: '(//ω//)', category: 'Shy', keywords: ['blush'] },
  { id: 'sh7', text: '(o_ _)ﾉ彡☆', category: 'Shy', keywords: ['laughing'] },
  { id: 'sh8', text: '(⁄ ⁄•⁄-⁄•⁄ ⁄)', category: 'Shy', keywords: ['blush'] },
  { id: 'sh9', text: '(*μ_μ)', category: 'Shy', keywords: ['shy'] },
  { id: 'sh10', text: '(◡‿◡✿)', category: 'Shy', keywords: ['shy'] },
  { id: 'sh11', text: '( 〃．．)', category: 'Shy', keywords: ['shy'] },
  { id: 'sh12', text: '(*ﾉ∀`*)', category: 'Shy', keywords: ['shy', 'laugh'] },
  { id: 'sh13', text: '(//▽//)', category: 'Shy', keywords: ['blush'] },
  { id: 'sh14', text: '(⁄ ⁄•⁄ ⁄•⁄ ⁄)', category: 'Shy', keywords: ['blush'] },
  { id: 'sh15', text: '(*/ω＼)', category: 'Shy', keywords: ['peek'] },

  // Sympathy (NEW - 10+)
  { id: 'sy1', text: '(´｡• ᵕ •｡`)', category: 'Sympathy', keywords: ['comfort'] },
  { id: 'sy2', text: '(o´･_･)っ', category: 'Sympathy', keywords: ['comfort', 'pat'] },
  { id: 'sy3', text: '(づ◡﹏◡)づ', category: 'Sympathy', keywords: ['hug'] },
  { id: 'sy4', text: '(つ . •́ _ʖ •̀ .)つ', category: 'Sympathy', keywords: ['hug'] },
  { id: 'sy5', text: '(っ´ω`)ﾉ(╥ω╥)', category: 'Sympathy', keywords: ['pat', 'cry'] },
  { id: 'sy6', text: '(･ω･)つ⊂(･ω･)', category: 'Sympathy', keywords: ['hug'] },
  { id: 'sy7', text: '( T_T)＼(^-^ )', category: 'Sympathy', keywords: ['there there'] },
  { id: 'sy8', text: '(..、)ヾ(^-^;) ', category: 'Sympathy', keywords: ['comfort'] },
  { id: 'sy9', text: '(づ｡◕‿‿◕｡)づ', category: 'Sympathy', keywords: ['hug'] },
  { id: 'sy10', text: '(*・ω・)ﾉ (._.`)', category: 'Sympathy', keywords: ['comfort'] },

  // Cute (15+)
  { id: 'cu1', text: '(◕‿◕)', category: 'Cute', keywords: ['cute', 'eyes'] },
  { id: 'cu2', text: '(uwu)', category: 'Cute', keywords: ['cute'] },
  { id: 'cu3', text: '(✿◠‿◠)', category: 'Cute', keywords: ['flower'] },
  { id: 'cu4', text: '(◡‿◡✿)', category: 'Cute', keywords: ['shy', 'flower'] },
  { id: 'cu5', text: '(*^ω^)', category: 'Cute', keywords: ['happy'] },
  { id: 'cu6', text: '(｡♥‿♥｡)', category: 'Cute', keywords: ['love'] },
  { id: 'cu7', text: '(*≧ω≦*)', category: 'Cute', keywords: ['happy'] },
  { id: 'cu8', text: '(◕ω◕✿)', category: 'Cute', keywords: ['eyes'] },
  { id: 'cu9', text: '(*・ω・)', category: 'Cute', keywords: ['cat face'] },
  { id: 'cu10', text: '(^・ω・^ )', category: 'Cute', keywords: ['cat'] },
  { id: 'cu11', text: '(｡･ω･｡)', category: 'Cute', keywords: ['cat'] },
  { id: 'cu12', text: '(●´ω｀●)', category: 'Cute', keywords: ['blush'] },
  { id: 'cu13', text: '(｡・//ε//・｡)', category: 'Cute', keywords: ['blush'] },
  { id: 'cu14', text: '(ღ˘⌣˘ღ)', category: 'Cute', keywords: ['peace'] },
  { id: 'cu15', text: '(✿ ♥‿♥)', category: 'Cute', keywords: ['love'] },

  // ... (Keep existing non-emotional categories - Animals, Greetings, etc. - they are already fine, but I must ensure they are included)
  // Action (15+)
  { id: 'ac1', text: '(╯°□°）╯︵ ┻━┻', category: 'Action', keywords: ['flip table', 'angry'] },
  { id: 'ac2', text: '┬─┬ノ( º _ ºノ)', category: 'Action', keywords: ['put table back'] },
  { id: 'ac3', text: '(/・0・)', category: 'Action', keywords: ['wave'] },
  { id: 'ac4', text: 'ε=ε=┌( >_<)┘', category: 'Action', keywords: ['running'] },
  { id: 'ac5', text: 'ᕙ(⇀‸↼‶)ᕗ', category: 'Action', keywords: ['flex', 'strong'] },
  { id: 'ac6', text: '(ノಠ益ಠ)ノ彡┻━┻', category: 'Action', keywords: ['flip table', 'furious'] },
  { id: 'ac7', text: '(/・・)ノ', category: 'Action', keywords: ['throw'] },
  { id: 'ac8', text: '( ´∀｀)ノ～ ♡', category: 'Action', keywords: ['throw love'] },
  { id: 'ac9', text: '(*・ω・)ﾉ', category: 'Action', keywords: ['wave'] },
  { id: 'ac10', text: 'ᕦ(ò_óˇ)ᕤ', category: 'Action', keywords: ['flex'] },

  // Dancing (10+)
  { id: 'da1', text: '♪ヽ( ⌒o⌒)人(⌒-⌒ )v ♪', category: 'Dancing', keywords: ['dance', 'party'] },
  { id: 'da2', text: '＼(￣▽￣)／', category: 'Dancing', keywords: ['yay'] },
  { id: 'da3', text: '♪♪♪ ヽ(ˇ∀ˇ )ゞ', category: 'Dancing', keywords: ['music'] },
  { id: 'da4', text: 'ヾ(･ω･*)ﾉ', category: 'Dancing', keywords: ['dance'] },
  { id: 'da5', text: '〜(￣▽￣〜)', category: 'Dancing', keywords: ['groove'] },
  { id: 'da6', text: '(〜￣△￣)〜', category: 'Dancing', keywords: ['ghost dance'] },
  { id: 'da7', text: 'ヽ(⌐■_■)ノ♪♬', category: 'Dancing', keywords: ['cool dance'] },
  { id: 'da8', text: '~(˘▽˘~)', category: 'Dancing', keywords: ['dance'] },
  { id: 'da9', text: '(~˘▽˘)~', category: 'Dancing', keywords: ['dance'] },
  { id: 'da10', text: '└(＾＾)┐', category: 'Dancing', keywords: ['walking'] },

  // Cats (20+)
  { id: 'cat1', text: '(^..^)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat2', text: '(=^･ω･^=)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat3', text: 'V(=^･ω･^=)v', category: 'Cats', keywords: ['cat', 'peace'] },
  { id: 'cat4', text: '(=^-ω-^=)', category: 'Cats', keywords: ['cat', 'sleep'] },
  { id: 'cat5', text: '(=｀ω´=)', category: 'Cats', keywords: ['cat', 'angry'] },
  { id: 'cat6', text: '(=^･ｪ･^=)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat7', text: '(=^..^=)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat8', text: '(^・x・^)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat9', text: '(=^ ◡ ^=)', category: 'Cats', keywords: ['cat', 'happy'] },
  { id: 'cat10', text: '>^///^<', category: 'Cats', keywords: ['cat', 'blush'] },
  { id: 'cat11', text: '(=①ω①=)', category: 'Cats', keywords: ['cat'] },
  { id: 'cat12', text: '/ᐠ｡ꞈ｡ᐟ\\', category: 'Cats', keywords: ['cat', 'cute'] },
  { id: 'cat13', text: '(=ｘェｘ=)', category: 'Cats', keywords: ['cat', 'dead'] },
  { id: 'cat14', text: '(=O*_*O=)', category: 'Cats', keywords: ['cat', 'dizzy'] },
  { id: 'cat15', text: '(=T.T=)', category: 'Cats', keywords: ['cat', 'sad'] },
  { id: 'cat16', text: '(^=◕ᴥ◕=^)', category: 'Cats', keywords: ['cat'] },

  // Bears (10+)
  { id: 'br1', text: '(ᵔᴥᵔ)', category: 'Bears', keywords: ['bear'] },
  { id: 'br2', text: 'ʕ•ᴥ•ʔ', category: 'Bears', keywords: ['bear'] },
  { id: 'br3', text: 'ʕ ᵔᴥᵔ ʔ', category: 'Bears', keywords: ['bear', 'happy'] },
  { id: 'br4', text: 'ʕ •̀ ω •́ ʔ', category: 'Bears', keywords: ['bear', 'determined'] },
  { id: 'br5', text: 'ʕ • ᴥ • ʔ', category: 'Bears', keywords: ['bear'] },
  { id: 'br6', text: 'ᶘ ᵒᴥᵒᶅ', category: 'Bears', keywords: ['bear', 'seal'] },
  { id: 'br7', text: 'ʕ º ᴥ º ʔ', category: 'Bears', keywords: ['bear'] },
  { id: 'br8', text: 'ʕ´•ᴥ•`ʔ', category: 'Bears', keywords: ['bear', 'sad'] },
  { id: 'br9', text: 'ʕ/　·ᴥ·ʔ/', category: 'Bears', keywords: ['bear', 'wave'] },
  { id: 'br10', text: 'ʕ·ᴥ·　ʔ', category: 'Bears', keywords: ['bear', 'look'] },

  // Dogs (10+)
  { id: 'dg1', text: '(U・x・U)', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg2', text: 'U・ᴥ・U', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg3', text: 'U ´ᴥ` U', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg4', text: '(U・ω・U)', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg5', text: 'U^ｪ^U', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg6', text: 'V●ᴥ●V', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg7', text: 'U(•ㅅ•)U', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg8', text: '(U・ﻌ・U)', category: 'Dogs', keywords: ['dog'] },
  { id: 'dg9', text: 'U •́ .̫ •̀ U', category: 'Dogs', keywords: ['dog', 'sad'] },
  { id: 'dg10', text: '(υ´• ﻌ •`υ)', category: 'Dogs', keywords: ['dog'] },

  // Rabbits (10+)
  { id: 'rb1', text: '／(･ × ･)＼', category: 'Rabbits', keywords: ['rabbit'] },
  { id: 'rb2', text: '／(≧ x ≦)＼', category: 'Rabbits', keywords: ['rabbit', 'happy'] },
  { id: 'rb3', text: 'U(•ㅅ•)U', category: 'Rabbits', keywords: ['rabbit'] },
  { id: 'rb4', text: '(x . x) ~~', category: 'Rabbits', keywords: ['rabbit', 'dead'] },
  { id: 'rb5', text: '／(^ x ^)＼', category: 'Rabbits', keywords: ['rabbit'] },
  { id: 'rb6', text: '／(･_･)＼', category: 'Rabbits', keywords: ['rabbit', 'normal'] },
  { id: 'rb7', text: '／(=･ x ･=)＼', category: 'Rabbits', keywords: ['rabbit'] },
  { id: 'rb8', text: '／(＞×＜)＼', category: 'Rabbits', keywords: ['rabbit', 'hurting'] },
  { id: 'rb9', text: '／(v x v)＼', category: 'Rabbits', keywords: ['rabbit', 'down'] },
  { id: 'rb10', text: '／(=´x`=)＼', category: 'Rabbits', keywords: ['rabbit', 'sleepy'] },

  // Greetings (10+)
  { id: 'gr1', text: '(・_・)ノ', category: 'Greetings', keywords: ['hello', 'wave'] },
  { id: 'gr2', text: '(^-^*)/', category: 'Greetings', keywords: ['hello', 'wave'] },
  { id: 'gr3', text: '( ´ ▽ ` )ﾉ', category: 'Greetings', keywords: ['hello', 'happy'] },
  { id: 'gr4', text: 'Hello ( ^_^)／', category: 'Greetings', keywords: ['hello', 'wave'] },
  { id: 'gr5', text: '(*・ω・)ﾉ', category: 'Greetings', keywords: ['wave'] },
  { id: 'gr6', text: '(=ﾟωﾟ)ﾉ', category: 'Greetings', keywords: ['hello'] },
  { id: 'gr7', text: '(≧▽≦)/', category: 'Greetings', keywords: ['yay'] },
  { id: 'gr8', text: '(・∀・)ノ', category: 'Greetings', keywords: ['hi'] },
  { id: 'gr9', text: 'ヾ(☆▽☆)', category: 'Greetings', keywords: ['hi'] },
  { id: 'gr10', text: '( ^_^)／', category: 'Greetings', keywords: ['hello'] },

  // Sleeping (10+)
  { id: 'sl1', text: '(￣o￣) zzZ', category: 'Sleeping', keywords: ['sleep', 'zzz'] },
  { id: 'sl2', text: '(－_－) zzZ', category: 'Sleeping', keywords: ['sleep', 'tired'] },
  { id: 'sl3', text: '(∪｡∪)｡｡｡zzz', category: 'Sleeping', keywords: ['sleep'] },
  { id: 'sl4', text: '(＿ ＿*) Z z z', category: 'Sleeping', keywords: ['sleep'] },
  { id: 'sl5', text: '[(－－)]..zzZ', category: 'Sleeping', keywords: ['sleep'] },
  { id: 'sl6', text: '(ｘ . ｘ) ...zzZ', category: 'Sleeping', keywords: ['knocked out'] },
  { id: 'sl7', text: '(=ω=)..nyaa', category: 'Sleeping', keywords: ['sleep', 'cat'] },
  { id: 'sl8', text: '(u_u)', category: 'Sleeping', keywords: ['sleep'] },
  { id: 'sl9', text: '(o_ _)o ᶻᶻᶻ', category: 'Sleeping', keywords: ['sleep'] },
  { id: 'sl10', text: '(￣ρ￣)..zzZ', category: 'Sleeping', keywords: ['sleep'] },

  // Apology (10+)
  { id: 'ap1', text: 'm(_ _)m', category: 'Apology', keywords: ['bow', 'sorry'] },
  { id: 'ap2', text: '(シ_ _)シ', category: 'Apology', keywords: ['bow', 'sorry', 'worship'] },
  { id: 'ap3', text: 'Sorry... (o_ _)o', category: 'Apology', keywords: ['sorry', 'fall'] },
  { id: 'ap4', text: '(人 •͈ᴗ•͈)', category: 'Apology', keywords: ['please', 'sorry'] },
  { id: 'ap5', text: '<(_ _)>', category: 'Apology', keywords: ['bow'] },
  { id: 'ap6', text: '( ._.)', category: 'Apology', keywords: ['sorry'] },
  { id: 'ap7', text: '(m;_ _)m', category: 'Apology', keywords: ['sweat', 'sorry'] },
  { id: 'ap8', text: '(≧人≦)', category: 'Apology', keywords: ['beg'] },
  { id: 'ap9', text: '(ノ_<、)', category: 'Apology', keywords: ['sorry', 'cry'] },
  { id: 'ap10', text: 'm(._.)m', category: 'Apology', keywords: ['sorry', 'bow'] },

  // Magic (10+)
  { id: 'mg1', text: '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧', category: 'Magic', keywords: ['magic', 'sparkle'] },
  { id: 'mg2', text: '☆*:.｡.o(≧▽≦)o.｡.:*☆', category: 'Magic', keywords: ['magic', 'excited'] },
  { id: 'mg3', text: '╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ', category: 'Magic', keywords: ['magic', 'wand'] },
  { id: 'mg4', text: '(∩^o^)⊃━☆', category: 'Magic', keywords: ['magic'] },
  { id: 'mg5', text: '━☆ﾟ.*･｡ﾟ', category: 'Magic', keywords: ['sparkle'] },
  { id: 'mg6', text: '(⊃｡•́‿•̀｡)⊃━☆ﾟ.*･｡ﾟ', category: 'Magic', keywords: ['spell'] },
  { id: 'mg7', text: '(∩｀-´)⊃━☆ﾟ.*･｡ﾟ', category: 'Magic', keywords: ['attack'] },
  { id: 'mg8', text: 'Bibbidi Bobbidi Boo *', category: 'Magic', keywords: ['spell'] },
  { id: 'mg9', text: '（＊’ー’）ノ☆', category: 'Magic', keywords: ['wand'] },
  { id: 'mg10', text: '( ・_・)ノ⌒●~*', category: 'Magic', keywords: ['bomb'] },

  // Food (10+)
  { id: 'fd1', text: '( ・∀・)っ旦', category: 'Food', keywords: ['tea', 'drink'] },
  { id: 'fd2', text: '(*・ω・)っiii', category: 'Food', keywords: ['cake', 'birthday'] },
  { id: 'fd3', text: '(っˆڡˆς)', category: 'Food', keywords: ['yummy'] },
  { id: 'fd4', text: '( ˘▽˘)っ♨', category: 'Food', keywords: ['hot food', 'tea'] },
  { id: 'fd5', text: '(o˘◡˘o) ┌iii┐', category: 'Food', keywords: ['cake'] },
  { id: 'fd6', text: '( ・ω・)o━<', category: 'Food', keywords: ['skewer'] },
  { id: 'fd7', text: '♨(⋆‿⋆)', category: 'Food', keywords: ['hot'] },
  { id: 'fd8', text: '(っ˘ڡ˘ς)', category: 'Food', keywords: ['yummy'] },
  { id: 'fd9', text: 'Ψ( `∀` )Ψ', category: 'Food', keywords: ['eat'] },
  { id: 'fd10', text: '( ˘▽˘)っ(⋆‿⋆)', category: 'Food', keywords: ['share'] },

  // Study (10+)
  { id: 'st1', text: 'φ(・ω・｀ )', category: 'Study', keywords: ['writing'] },
  { id: 'st2', text: '...φ(︶▽︶)φ...', category: 'Study', keywords: ['writing', 'happy'] },
  { id: 'st3', text: '〆(・∀・｀)', category: 'Study', keywords: ['writing'] },
  { id: 'st4', text: '✎ (❁ᴗ͈ˬᴗ͈) ༉‧ ♡*.✧', category: 'Study', keywords: ['writing', 'cute'] },
  { id: 'st5', text: '___〆(・∀・)', category: 'Study', keywords: ['writing'] },
  { id: 'st6', text: '(￣ー￣)φ__', category: 'Study', keywords: ['writing'] },
  { id: 'st7', text: 'φ(￣ー￣ )ノ', category: 'Study', keywords: ['writing'] },
  { id: 'st8', text: '( ˙-˙ )✎', category: 'Study', keywords: ['writing'] },
  { id: 'st9', text: '...φ(。。*)', category: 'Study', keywords: ['taking notes'] },
  { id: 'st10', text: 'φ(◎◎ヘ)', category: 'Study', keywords: ['studying hard'] },

  // Music (10+)
  { id: 'mu1', text: '♪♪♪ ヽ(ˇ∀ˇ )ゞ', category: 'Music', keywords: ['dancing', 'music'] },
  { id: 'mu2', text: '♬♫♪◖(●◡●)◗♪♫♬', category: 'Music', keywords: ['headphones', 'music'] },
  { id: 'mu3', text: '♪(┌・。・)┌', category: 'Music', keywords: ['dancing'] },
  { id: 'mu4', text: '(^_^♪)', category: 'Music', keywords: ['music'] },
  { id: 'mu5', text: 'v(⌒o⌒)v♪', category: 'Music', keywords: ['peace', 'music'] },
  { id: 'mu6', text: '♪└|∵|┐♪', category: 'Music', keywords: ['dancing'] },
  { id: 'mu7', text: '(~˘▽˘)~', category: 'Music', keywords: ['vibe'] },
  { id: 'mu8', text: '♪♪(o*゜∇゜)o～♪♪', category: 'Music', keywords: ['singing'] },
  { id: 'mu9', text: '( *´・ω)/(；д； )', category: 'Music', keywords: ['comfort', 'music?'] },
  { id: 'mu10', text: '♪ヽ( ⌒o⌒)人(⌒-⌒ )v ♪', category: 'Music', keywords: ['party'] },

  // Friends (10+)
  { id: 'fr1', text: 'ヽ( ⌒o⌒)人(⌒-⌒ )ﾉ', category: 'Friends', keywords: ['high five'] },
  { id: 'fr2', text: '(*・∀・)爻(・∀・*)', category: 'Friends', keywords: ['high five'] },
  { id: 'fr3', text: '╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ', category: 'Friends', keywords: ['magic'] },
  { id: 'fr4', text: '(=´∀`)人(´∀`=)', category: 'Friends', keywords: ['high five'] },
  { id: 'fr5', text: '(・_・)ノ (・_・)ノ', category: 'Friends', keywords: ['hello'] },
  { id: 'fr6', text: '( ´∀｀)人(´∀｀ )', category: 'Friends', keywords: ['high five'] },
  { id: 'fr7', text: '(*^o^)人(^o^*)', category: 'Friends', keywords: ['high five'] },
  { id: 'fr8', text: '( ｡･_･｡)人(｡･_･｡ )', category: 'Friends', keywords: ['shy'] },
  { id: 'fr9', text: 'ヽ(∀° )人( °∀)ノ', category: 'Friends', keywords: ['high five'] },
  { id: 'fr10', text: '(((￣(￣(￣▽￣)￣)￣)))', category: 'Friends', keywords: ['crowd'] },
]

export function getKaomojis(category?: string | null, search?: string, customList: Kaomoji[] = []): Kaomoji[] {
  // Merge static list with custom list (custom first or last? let's do last but clearly categorized)
  // Ensure custom items map to the Kaomoji interface if needed, but they should match.
  let list = [...customList, ...KAOMOJI_LIST]
  
  if (category && category !== 'All') {
    list = list.filter(k => k.category === category)
  }

  if (search) {
    const term = search.toLowerCase()
    list = list.filter(k => 
      k.text.toLowerCase().includes(term) || 
      k.keywords.some(key => key.includes(term)) ||
      k.category.toLowerCase().includes(term)
    )
  }
  
  return list
}
